DROP TABLE MEMBER;

--회원테이블 
--아이디, 비밀번호, 이름, 전화번호, 주소, 이메일, 회원상태, 회원등급
CREATE TABLE MEMBER(
	MEMBER_ID VARCHAR2(400) PRIMARY KEY,
	MEMBER_PW VARCHAR2(1000) NOT NULL,
	MEMBER_NAME VARCHAR2(200) NOT NULL, 
	MEMBER_PHONE VARCHAR2(600) NOT NULL,
	MEMBER_ADDRESS VARCHAR2(1000) NOT NULL,
	MEMBER_EMAIL VARCHAR2(1000) NOT NULL,
	MEMBER_ENABLED VARCHAR2(2) NOT NULL,
	MEMBER_LEVEL VARCHAR2(20) NOT NULL,
	CONSTRAINT MEMBER_ENABLED_CK CHECK (MEMBER_ENABLED IN('Y','N'))
);

SELECT * FROM MEMBER;
