DROP TABLE MEMBER;

CREATE TABLE MEMBER(
	MEMBER_ID VARCHAR2(400) PRIMARY KEY,
	MEMBER_PW VARCHAR2(1000) NOT NULL,
	MEMBER_NAME VARCHAR2(200) NOT NULL, 
	MEMBER_PHONE VARCHAR2(600) NOT NULL,
	MEMBER_ADDRESS VARCHAR2(1000) NOT NULL,
	MEMBER_EMAIL VARCHAR2(1000) NOT NULL,
	MEMBER_ENABLED VARCHAR2(2) NOT NULL,
	MEMBER_LEVEL VARCHAR2(20) NOT NULL,
	CONSTRAINT MEMBER_ENABLED_CK CHECK (MEMBER_ENABLED IN('Y','N'))
);

SELECT * FROM MEMBER;

insert into member values('admin', 'admin123', '관리자', '01011111111', '서울시 강남구 역삼동', 'ad.team555@gmail.com', 'Y', 'ADMIN');


CREATE TABLE TESTDB(
	MEMBER_ID VARCHAR2(400) PRIMARY KEY,
	MEMBER_PW VARCHAR2(1000) NOT NULL,
	MEMBER_NAME VARCHAR2(200) NOT NULL, 
	MEMBER_PHONE VARCHAR2(600) NOT NULL,
	MEMBER_ADDRESS VARCHAR2(1000) NOT NULL,
	MEMBER_EMAIL VARCHAR2(1000) NOT NULL,
	MEMBER_ENABLED VARCHAR2(2) NOT NULL,
	MEMBER_LEVEL VARCHAR2(20) NOT NULL,
	CONSTRAINT TESTDB_ENABLED_CK CHECK (MEMBER_ENABLED IN('Y','N'))
);