/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.16
 * Generated at: 2019-06-13 07:29:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board_005fmember;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_005fmypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"viewport\" content=\"height=device-height, initial-scale=1.0\">\r\n");
      out.write("<title>Hippe || 대한민국 가장 힙한 페스티벌, 히페 :: 마이페이지 :: </title>\r\n");
      out.write("  <link href=\"http://localhost:8787/Hippe/resources/css/member_mypage.css\" rel=\"stylesheet\" type=\"text/css\" >\r\n");
      out.write("  <!--booststrap-->\r\n");
      out.write("  <link href=\"http://localhost:8787/Hippe/resources/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\r\n");
      out.write("  <!--//booststrap end-->\r\n");
      out.write("  <!-- font-awesome icons -->\r\n");
      out.write("  <link href=\"http://localhost:8787/Hippe/resources/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- //font-awesome icons -->\r\n");
      out.write("  <!--stylesheets-->\r\n");
      out.write("  <link href=\"http://localhost:8787/Hippe/resources/css/style.css\" rel='stylesheet' type='text/css' media=\"all\">\r\n");
      out.write("  <!--//stylesheets-->\r\n");
      out.write("  <link href=\"//fonts.googleapis.com/css?family=Josefin+Sans:400,600,700\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"//fonts.googleapis.com/css?family=Libre+Franklin:400,500\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/hippe_header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"div_mid\">\r\n");
      out.write("\t\t<div class=\"div_box\" id=\"mypage\">\r\n");
      out.write("\t\t\t<label class=\"box_label\">회원정보수정</label>\r\n");
      out.write("\t\t\t<img id=\"mypage_img\" src=\"../resources/images/User.png\" alt=\"마이페이지\"/>\t\t\r\n");
      out.write("\t\t\t<div id=\"modify\">수   정</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<!--  -->\t\r\n");
      out.write("\t\t<div class=\"div_box\" id=\"reservations\">\r\n");
      out.write("\t\t\t<label class=\"box_label\">예매 확인/취소</label>\r\n");
      out.write("\t\t\t<div id=\"reservations2\">예매확인</div>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t<!--  -->\t\r\n");
      out.write("\t\t<div class=\"div_box\" id=\"bookmark\">\r\n");
      out.write("\t\t\t<label id=\"box_label\">즐겨찾기</label>\r\n");
      out.write("\t\t\t<div id=\"modify2\">확   인</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t<!--  -->\t\t\r\n");
      out.write("\t\t<div class=\"div_box\" id=\"leave\">\r\n");
      out.write("\t\t\t<label id=\"box_label\">회원탈퇴</label>\r\n");
      out.write("\t\t\t<div id=\"modify3\">회원탈퇴</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!--  -->\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
