/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.16
 * Generated at: 2019-06-13 07:27:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hippe_005fmain;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class hippe_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Hippe || 대한민국 가장 힙한 페스티벌, 히페 :: Home :: </title>\n");
      out.write("<!--meta tags -->\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta name=\"keywords\" content=\"Yield Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\"/>\n");
      out.write("  <!--stylesheets-->\n");
      out.write("  <link href=\"../resources/css/style.css\" rel='stylesheet' type='text/css' media=\"all\">\t\n");
      out.write("  <!--booststrap-->\n");
      out.write("  <link href=\"../resources/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\n");
      out.write("  <!-- font-awesome icons -->\n");
      out.write("  <link href=\"../resources/css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("  <!-- Google Web Font -->\n");
      out.write("  <link href=\"//fonts.googleapis.com/css?family=Josefin+Sans:400,600,700\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"//fonts.googleapis.com/css?family=Libre+Franklin:400,500\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"jquery.bxslider/jquery.bxslider.css\" rel=\"stylesheet\" /> \n");
      out.write("  <script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js\"></script> \n");
      out.write("  <script src=\"jquery.bxslider/jquery.bxslider.js\"></script>\n");
      out.write("<script>\n");
      out.write("    addEventListener(\"load\", function () {\n");
      out.write("      setTimeout(hideURLbar, 0);\n");
      out.write("    }, false);\n");
      out.write("\n");
      out.write("    function hideURLbar() {\n");
      out.write("    \twindow.scrollTo(0, 1);\n");
      out.write("    }\n");
      out.write("\n");
      out.write(" \n");
      out.write("    $(document).ready(function() {\n");
      out.write("    \tvar slider = $('.bxslider').bxSlider({\n");
      out.write("    \t\tauto: true, \n");
      out.write("    \t\tspeed: 2000, \n");
      out.write("    \t\tpause: 2000, \n");
      out.write("    \t\tmode:'fade', \n");
      out.write("    \t\tautoControls: false, \n");
      out.write("    \t\tpager:true,\n");
      out.write("    \t}); \n");
      out.write("    \t\n");
      out.write("    \tvar mql = window.matchMedia(\"screen and (max-width: 768px)\"); \n");
      out.write("    \tmql.addListener(function(e) { \n");
      out.write("    \t\tif(!e.matches) { \n");
      out.write("    \t\t\tslider.reloadSlider(); \n");
      out.write("    \t\t} \n");
      out.write("    \t});\n");
      out.write("    });\n");
      out.write("    \n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- Header -->\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/hippe_header.jsp", out, false);
      out.write('\n');
      out.write('	');
      out.write("\n");
      out.write("  <!-- Slider -->\n");
      out.write("  <div class=\"main-top\" id=\"home\">\n");
      out.write("  \t<div>\n");
      out.write("  \t<ul class=\"bxslider\">\n");
      out.write("  \t\t<li>\n");
      out.write("  \t\t\t<div class=\"container\">\n");
      out.write("        \t\t<div class=\"slider-info\">\n");
      out.write("         \t\t\t<h4>대한민국 힙한 페스티벌</h4>\n");
      out.write("          \t\t\t<h1>히페(Hippe)</h1>\n");
      out.write("          \t\t\t<p>대한민국 전역에서 열리는 힙~한 페스티벌, 여기서 모두 만나보세요!</p>\n");
      out.write("        \t\t</div>\n");
      out.write("        \t\t<div class=\"outs_more-buttn mt-md-4 mt-3\">\n");
      out.write("          \t\t\t<a href=\"../festivalController.do?command=list\">더 보러가기</a>\n");
      out.write("        \t\t</div>\n");
      out.write("      \t\t</div>\n");
      out.write("  \t\t\t<img class=\"img_main\" src=\"../resources/images/bgd01.png\">\n");
      out.write("  \t\t</li>\n");
      out.write("  \t\t<li><a><img class=\"img_main\" src=\"../resources/images/bgd02.png\"></a></li>\n");
      out.write("  \t\t<li><a><img class=\"img_main\" src=\"../resources/images/bgd03.png\"></a></li>\n");
      out.write("  \t\t<li><a><img class=\"img_main\" src=\"../resources/images/bgd04.png\"></a></li>\n");
      out.write("  \t</ul>\n");
      out.write("  \t</div>\n");
      out.write("<!--     <div class=\"slider-img \">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"slider-info\">\n");
      out.write("          <h4>대한민국 힙한 페스티벌</h4>\n");
      out.write("          <h1>히페(Hippe)</h1>\n");
      out.write("          <p>대한민국 전역에서 열리는 힙~한 페스티벌, 여기서 모두 만나보세요!</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"outs_more-buttn mt-md-4 mt-3\">\n");
      out.write("          <a href=\"../festivalController.do?command=list\">더 보러가기</a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div> -->\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <!-- Calendar -->\n");
      out.write("  <section class=\"about py-lg-4 py-md-3 py-sm-3 py-3\" id=\"about\">\n");
      out.write("    <div class=\"container py-lg-5 py-md-4 py-sm-4 py-3\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-lg-6 about-imgs-txt my-3\">\n");
      out.write("          <img src=\"../resources/images/calendar-img.png\" alt=\"news image\" class=\"img-fluid\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-6 about-two-grids my-3\">\n");
      out.write("          <h5 class=\"top-title mb-lg-4 mb-3\"> About</h5>\n");
      out.write("          <h2 class=\"mb-md-3 mb-sm-3 mb-3\">We are organic farm food.live organic for live healthy 100% organic goods</h2>\n");
      out.write("          <div class=\"about-para-txt\">\n");
      out.write("            <p>sed do eiusmod tempor incididunt ut Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet, eiusmod tempor incididunt\n");
      out.write("              ut labore consectetur adipiscing sed do eiusmod tempor incididunt ut Lorem ipsum dolor sit amet Lorem ipsum\n");
      out.write("              dolor sit amet consectetur adipiscing sed do eiusmod tempor incididunt ut Lorem ipsum dolor sit amet </p>\n");
      out.write("          </div>\n");
      out.write("          <h6 class=\"my-lg-5 my-md-4 my-3\">fresh from Yield farm</h6>\n");
      out.write("          <div class=\"about-para-txt\">\n");
      out.write("            <p>sed do eiusmod tempor incididunt ut Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet, eiusmod tempor incididunt\n");
      out.write("              ut labore et consectetur adipiscing sed do eiusmod tempor incididunt</p>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"outs_more-buttn mt-md-4 mt-3\">\n");
      out.write("            <a href=\"#blog\">더 보러가기</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("\n");
      out.write("   <!-- Ticket Matter 영역 -->\n");
      out.write("  <section class=\"advertise-count py-lg-4 py-md-3 py-sm-3 py-3\">\n");
      out.write("    <div class=\"container py-lg-5 py-md-4 py-sm-4 py-3\">\n");
      out.write("      <div class=\"order-show-w3ls \">\n");
      out.write("        <h4>10 Health Benefits: What Secrets Do Watermelons Keep?</h4>\n");
      out.write("        <div class=\"outs_more-buttn mt-md-4 mt-3\">\n");
      out.write("          <a href=\"#contact\">예매하러 가기</a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("  <!-- TicketBox 영역 -->\n");
      out.write("  <section class=\"aboutTicket py-lg-4 py-md-3 py-sm-3 py-3\" id=\"about\">\n");
      out.write("    <div class=\"container py-lg-5 py-md-4 py-sm-4 py-3\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-lg-6 about-imgs-txt my-3\">\n");
      out.write("          <img src=\"../resources/images/calendar-img.png\" alt=\"news image\" class=\"img-fluid\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-6 about-two-grids my-3\">\n");
      out.write("          <h3 class=\"title mb-lg-5 mb-md-4 mb-sm-4 mb-3 text-center\">Ticket</h3>\n");
      out.write("          <h3 class=\"title mb-lg-5 mb-md-4 mb-sm-4 mb-3 text-center\">티켓목록 미리보기 보여주기</h3>\n");
      out.write("          <h2 class=\"mb-md-3 mb-sm-3 mb-3\">We are organic farm food.live organic for live healthy 100% organic goods</h2>\n");
      out.write("          <div class=\"about-para-txt\">\n");
      out.write("            <p>sed do eiusmod tempor incididunt ut Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet, eiusmod tempor incididunt\n");
      out.write("              ut labore consectetur adipiscing sed do eiusmod tempor incididunt ut Lorem ipsum dolor sit amet Lorem ipsum\n");
      out.write("              dolor sit amet consectetur adipiscing sed do eiusmod tempor incididunt ut Lorem ipsum dolor sit amet </p>\n");
      out.write("          </div>\n");
      out.write("          <h6 class=\"my-lg-5 my-md-4 my-3\">fresh from Yield farm</h6>\n");
      out.write("          <div class=\"about-para-txt\">\n");
      out.write("            <p>sed do eiusmod tempor incididunt ut Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet, eiusmod tempor incididunt\n");
      out.write("              ut labore et consectetur adipiscing sed do eiusmod tempor incididunt</p>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"outs_more-buttn mt-md-4 mt-3\">\n");
      out.write("            <a href=\"#blog\">더 보러가기</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("  \n");
      out.write("  <!-- Review -->\n");
      out.write("  <section class=\"gallery py-lg-4 py-md-3 py-sm-3 py-3\" id=\"gallery\">\n");
      out.write("    <div class=\"container py-lg-5 py-md-4 py-sm-4 py-3\">\n");
      out.write("      <h3 class=\"title mb-lg-5 mb-md-4 mb-sm-4 mb-3 text-center\">Reviews</h3>\n");
      out.write("      <h3 class=\"top-title mb-lg-4 mb-3 text-center\">여행지의 다양한 소식을 받아보세요!</h3>\n");
      out.write("      <div class=\"row gallery-info no-gutters\">\n");
      out.write("        <div class=\"col-lg-4 col-md-6 col-sm-6 gallery-img-grid \">\n");
      out.write("          <div class=\"gallery-grids\">\n");
      out.write("            <a href=\"#gal1\">\n");
      out.write("              <img src=\"../resources/images/g1.jpg\" alt=\"news image\" class=\"img-fluid\">\n");
      out.write("            </a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-4 col-md-6 col-sm-6 gallery-img-grid \">\n");
      out.write("          <div class=\"gallery-grids\">\n");
      out.write("            <a href=\"#gal2\">\n");
      out.write("              <img src=\"../resources/images/g6.jpg\" alt=\"news image\" class=\"img-fluid\">\n");
      out.write("            </a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-4 col-md-6 col-sm-6 gallery-img-grid\">\n");
      out.write("          <div class=\"gallery-grids\">\n");
      out.write("            <a href=\"#gal3\">\n");
      out.write("              <img src=\"../resources/images/g3.jpg\" alt=\"news image\" class=\"img-fluid\">\n");
      out.write("            </a>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-4 col-md-6 col-sm-6 gallery-img-grid\">\n");
      out.write("          <div class=\"gallery-grids\">\n");
      out.write("            <a href=\"#gal4\">\n");
      out.write("              <img src=\"../resources/images/g4.jpg\" alt=\"news image\" class=\"img-fluid\">\n");
      out.write("            </a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-4 col-md-6 col-sm-6 gallery-img-grid \">\n");
      out.write("          <div class=\"gallery-grids\">\n");
      out.write("            <a href=\"#gal5\">\n");
      out.write("              <img src=\"../resources/images/g2.jpg\" alt=\"news image\" class=\"img-fluid\">\n");
      out.write("            </a>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-4 col-md-6 col-sm-6 gallery-img-grid \">\n");
      out.write("          <div class=\"gallery-grids\">\n");
      out.write("            <a href=\"#gal6\">\n");
      out.write("              <img src=\"../resources/images/g5.jpg\" alt=\"news image\" class=\"img-fluid\">\n");
      out.write("            </a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- popup-->\n");
      out.write("        <div id=\"gal1\" class=\"popup-effect\">\n");
      out.write("          <div class=\"popup\">\n");
      out.write("            <img src=\"../resources/images/g1.jpg\" alt=\"Popup Image\" class=\"img-fluid\" />\n");
      out.write("            <a class=\"close\" href=\"#gallery\">&times;</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- //popup -->\n");
      out.write("        <!-- popup-->\n");
      out.write("        <div id=\"gal2\" class=\"popup-effect\">\n");
      out.write("          <div class=\"popup\">\n");
      out.write("            <img src=\"images/g6.jpg\" alt=\"Popup Image\" class=\"img-fluid\" />\n");
      out.write("            <a class=\"close\" href=\"#gallery\">&times;</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- //popup -->\n");
      out.write("        <!-- popup-->\n");
      out.write("        <div id=\"gal3\" class=\"popup-effect\">\n");
      out.write("          <div class=\"popup\">\n");
      out.write("            <img src=\"images/g3.jpg\" alt=\"Popup Image\" class=\"img-fluid\" />\n");
      out.write("            <a class=\"close\" href=\"#gallery\">&times;</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- //popup -->\n");
      out.write("        <!-- popup-->\n");
      out.write("        <div id=\"gal4\" class=\"popup-effect\">\n");
      out.write("          <div class=\"popup\">\n");
      out.write("            <img src=\"images/g4.jpg\" alt=\"Popup Image\" class=\"img-fluid\" />\n");
      out.write("            <a class=\"close\" href=\"#gallery\">&times;</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- //popup -->\n");
      out.write("        <!-- popup-->\n");
      out.write("        <div id=\"gal5\" class=\"popup-effect\">\n");
      out.write("          <div class=\"popup\">\n");
      out.write("            <img src=\"images/g2.jpg\" alt=\"Popup Image\" class=\"img-fluid\" />\n");
      out.write("            <a class=\"close\" href=\"#gallery\">&times;</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- //popup -->\n");
      out.write("        <!-- popup-->\n");
      out.write("        <div id=\"gal6\" class=\"popup-effect\">\n");
      out.write("          <div class=\"popup\">\n");
      out.write("            <img src=\"images/g5.jpg\" alt=\"Popup Image\" class=\"img-fluid\" />\n");
      out.write("            <a class=\"close\" href=\"#gallery\">&times;</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- //popup -->\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("  <!--//Reivew  -->\n");
      out.write("  \n");
      out.write("  <!-- Event  -->\n");
      out.write("  <section class=\"blog py-lg-4 py-md-3 py-sm-3 py-3\" id=\"blog\">\n");
      out.write("    <div class=\"container-fluid py-lg-5 py-md-4 py-sm-4 py-3\">\n");
      out.write("      <h3 class=\"title mb-lg-5 mb-md-4 mb-sm-4 mb-3 text-center\">Events</h3>\n");
      out.write("      <h5 class=\"top-title mb-lg-4 mb-3 text-center\">Hippe의 다양한 이벤트도 참여해보세요!</h5>\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-lg-6 blog-first-grid\">\n");
      out.write("          <div class=\"blog-txt text-center\">\n");
      out.write("            <h5>\n");
      out.write("              <a href=\"#about\">Arrived Fresh Lemons </a>\n");
      out.write("            </h5>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-6 bolg-right-grids\">\n");
      out.write("          <h4 class=\"pb-3\">\n");
      out.write("            <a href=\"#about\">Health Benefits of a Raw Food</a>\n");
      out.write("          </h4>\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nibh urna, euismod ut ornare non Lorem ipsum\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nibh urna, euismod ut ornare non Lorem ipsum\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nibh urna, euismod ut ornare non Lorem ipsum\n");
      out.write("          </p>\n");
      out.write("          <div class=\"mt-3 blog-date-time\">\n");
      out.write("            <ul>\n");
      out.write("              <li class=\"mr-3\">Comments\n");
      out.write("                <a href=\"#about\" class=\"pl-1\">7</a>\n");
      out.write("              </li>\n");
      out.write("              <li>Views\n");
      out.write("                <a href=\"#about\" class=\"pl-1\">5</a>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"outs_more-buttn mt-md-4 mt-3\">\n");
      out.write("            <a href=\"#about\">자세히 보기</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-6 bolg-right-grids text-md-right\">\n");
      out.write("          <h4 class=\"pb-3\">\n");
      out.write("            <a href=\"#about\">6 After-School Snacks the Kid Will Love</a>\n");
      out.write("          </h4>\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nibh urna, euismod ut ornare non Lorem ipsum\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nibh urna, euismod ut ornare non Lorem ipsum\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nibh urna, euismod ut ornare non Lorem ipsum\n");
      out.write("          </p>\n");
      out.write("          <div class=\"mt-3 blog-date-time\">\n");
      out.write("            <ul>\n");
      out.write("              <li class=\"mr-3\">Comments\n");
      out.write("                <a href=\"#about\" class=\"pl-1\">7</a>\n");
      out.write("              </li>\n");
      out.write("              <li>Views\n");
      out.write("                <a href=\"#about\" class=\"pl-1\">5</a>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"outs_more-buttn mt-md-4 mt-3\">\n");
      out.write("            <a href=\"#about\">자세히 보기</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-6 blog-second-grid\">\n");
      out.write("          <div class=\"blog-txt text-center\">\n");
      out.write("            <h5>\n");
      out.write("              <a href=\"#about\">Sweet & Fresh Strawberry</a>\n");
      out.write("            </h5>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("  <!--//blog -->\n");
      out.write("  \n");
      out.write("  <!-- contact -->\n");
      out.write("  <section class=\"contact\" id=\"contact\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("\n");
      out.write("        <div class=\"col-lg-7 col-md-6 contact-form-txt\">\n");
      out.write("          <form action=\"#\" method=\"post\">\n");
      out.write("            <div class=\"form-group contact-forms\">\n");
      out.write("              <input type=\"text\" class=\"form-control\" placeholder=\"Name\" required=\"\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group contact-forms\">\n");
      out.write("              <input type=\"email\" class=\"form-control\" placeholder=\"Email\" required=\"\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group contact-forms\">\n");
      out.write("              <input type=\"text\" class=\"form-control\" placeholder=\"Phone\" required=\"\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group contact-forms\">\n");
      out.write("              <textarea class=\"form-control\" placeholder=\"Message\" rows=\"3\" required=\"\"></textarea>\n");
      out.write("            </div>\n");
      out.write("            <button type=\"submit\" class=\"btn sent-butnn\">Send</button>\n");
      out.write("          </form>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-5 contact-grided-right\">\n");
      out.write("          <h5 class=\"top-title mb-lg-4 mb-3 text-center\">Contact Us</h5>\n");
      out.write("          <h3 class=\"title mb-lg-5 mb-md-4 mb-sm-4 mb-3 text-center\">Get In Touch</h3>\n");
      out.write("          <div class=\" footer-top text-center\">\n");
      out.write("            <p>\n");
      out.write("              <span>Address</span> : Melbourne St,South\n");
      out.write("              <br>Birbane 4101 Austraila.</p>\n");
      out.write("            <p class=\"pt-lg-3 pt-2\">\n");
      out.write("              <span> Phone</span> : +(000) 123 4565 32</p>\n");
      out.write("            <p class=\"pt-lg-3 pt-2\">\n");
      out.write("              <span>Email</span> :\n");
      out.write("              <a href=\"mailto:info@example.com\">info@example1.com</a>\n");
      out.write("            </p>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("  <!--//contact -->\n");
      out.write("  <!--  footer -->\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/hippe_footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
