/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.16
 * Generated at: 2019-06-13 07:44:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board_005freservation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ticket_005freserve_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write('\n');
 response.setContentType("text/html; charset=UTF-8"); 
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta name=\"viewport\" content=\"height=device-height, initial-scale=1\">\n");
      out.write("<title>Hippe || 대한민국 가장 힙한 페스티벌, 히페 :: 티켓 예매 ::</title>\n");
      out.write("<link href=\"../resources/css/board_ticket_style.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<!--booststrap-->\n");
      out.write("<link href=\"../resources/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\n");
      out.write("<!--//booststrap end-->\n");
      out.write("<!-- font-awesome icons -->\n");
      out.write("<link href=\"../resources/css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("<!-- //font-awesome icons -->\n");
      out.write("<!--stylesheets-->\n");
      out.write("<link href=\"../resources/css/style.css\" rel='stylesheet' type='text/css' media=\"all\">\n");
      out.write("<!--//stylesheets-->\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Josefin+Sans:400,600,700\" rel=\"stylesheet\">\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Libre+Franklin:400,500\" rel=\"stylesheet\">\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.4.0.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- header파일 포함 -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/hippe_header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"div_display\">\n");
      out.write("\t<br><br><br><br><br><br>전광판같이!!\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<div class=\"div_ticketbox\">\n");
      out.write("\t\t<div class=\"pamphlet\">\n");
      out.write("\t\t\t<img class=\"img_poster\" alt=\"img\" src=\"../resources/images/ticket_img01.png\">\n");
      out.write("\t\t\t<label class=\"txt_info\">2019 슬로우워킹 페스티벌</label>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"pamphlet\">\n");
      out.write("\t\t\t<img class=\"img_poster\" alt=\"img\" src=\"../resources/images/ticket_img02.png\">\n");
      out.write("\t\t\t<label class=\"txt_info\">경복궁 야간개장 특별관람</label>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"pamphlet\">\n");
      out.write("\t\t\t<img class=\"img_poster\" alt=\"img\" src=\"../resources/images/ticket_img03.png\">\n");
      out.write("\t\t\t<label class=\"txt_info\">호러나민C 페스티벌</label>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"pamphlet\">\n");
      out.write("\t\t\t<img class=\"img_poster\" alt=\"img\" src=\"../resources/images/ticket_img04.png\">\n");
      out.write("\t\t\t<label class=\"txt_info\">덕수궁 돌담길 야행</label>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"pamphlet\">\n");
      out.write("\t\t\t<img class=\"img_poster\" alt=\"img\" src=\"../resources/images/ticket_img01.png\">\n");
      out.write("\t\t\t<label class=\"txt_info\">2019 슬로우워킹 페스티벌</label>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"pamphlet\">\n");
      out.write("\t\t\t<img class=\"img_poster\" alt=\"img\" src=\"../resources/images/ticket_img02.png\">\n");
      out.write("\t\t\t<label class=\"txt_info\">경복궁 야간개장 특별관람</label>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"pamphlet\">\n");
      out.write("\t\t\t<img class=\"img_poster\" alt=\"img\" src=\"../resources/images/ticket_img03.png\">\n");
      out.write("\t\t\t<label class=\"txt_info\">호러나민C 페스티벌</label>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"pamphlet\">\n");
      out.write("\t\t\t<img class=\"img_poster\" alt=\"img\" src=\"../resources/images/ticket_img04.png\">\n");
      out.write("\t\t\t<label class=\"txt_info\">덕수궁 돌담길 야행</label>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"pamphlet\">\n");
      out.write("\t\t\t<img class=\"img_poster\" alt=\"img\" src=\"../resources/images/ticket_img01.png\">\n");
      out.write("\t\t\t<label class=\"txt_info\">2019 슬로우워킹 페스티벌</label>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"pamphlet\">\n");
      out.write("\t\t\t<img class=\"img_poster\" alt=\"img\" src=\"../resources/images/ticket_img02.png\">\n");
      out.write("\t\t\t<label class=\"txt_info\">경복궁 야간개장 특별관람</label>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"pamphlet\">\n");
      out.write("\t\t\t<img class=\"img_poster\" alt=\"img\" src=\"../resources/images/ticket_img03.png\">\n");
      out.write("\t\t\t<label class=\"txt_info\">호러나민C 페스티벌</label>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"pamphlet\">\n");
      out.write("\t\t\t<img class=\"img_poster\" alt=\"img\" src=\"../resources/images/ticket_img04.png\">\n");
      out.write("\t\t\t<label class=\"txt_info\">덕수궁 돌담길 야행</label>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<br><br><br><br><br>\t\n");
      out.write("\n");
      out.write("\t<!--  footer -->\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/hippe_footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
