/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.16
 * Generated at: 2019-06-13 07:27:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class hippe_005ffooter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<title></title>\n");
      out.write("</head>\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.4.0.min.js\"></script>\n");
      out.write(" <script>\n");
      out.write("    addEventListener(\"load\", function () {\n");
      out.write("      setTimeout(hideURLbar, 0);\n");
      out.write("    }, false);\n");
      out.write("\n");
      out.write("    function hideURLbar() {\n");
      out.write("      window.scrollTo(0, 1);\n");
      out.write("    }\n");
      out.write("    function gotoLogin(){\n");
      out.write("    \tlocation.href=\"/Hippe/memberController.do?command=loginBtn\";\n");
      out.write("    }\n");
      out.write("    function gotoSignup(){\n");
      out.write("    \tlocation.href=\"/Hippe/memberController.do?command=signupBtn\";\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("<!--booststrap-->\n");
      out.write("  <link href=\"../resources/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\n");
      out.write("  <!--//booststrap end-->\n");
      out.write("  <!-- font-awesome icons -->\n");
      out.write("  <link href=\"../resources/css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("  <!-- //font-awesome icons -->\n");
      out.write("  <!--stylesheets-->\n");
      out.write("  <link href=\"/Hippe/resources/css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\n");
      out.write("  <!--//stylesheets-->\n");
      out.write("  <link href=\"//fonts.googleapis.com/css?family=Josefin+Sans:400,600,700\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"//fonts.googleapis.com/css?family=Libre+Franklin:400,500\" rel=\"stylesheet\">\n");
      out.write("<body>\n");
      out.write("<!-- footer -->\n");
      out.write("  <section class=\"footer-grids py-lg-4 py-md-3 py-sm-3 py-3\">\n");
      out.write("    <div class=\"container py-lg-5 py-md-5 py-sm-4 py-3\">\n");
      out.write("      <div class=\"footer-w3layouts-head text-center\">\n");
      out.write("        <h5>About Us</h5>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"footer-icons mt-md-4 mt-3 text-center\">\n");
      out.write("        <ul>\n");
      out.write("          <li>\n");
      out.write("            <a href=\"#\">\n");
      out.write("              <span class=\"fa fa-facebook\"></span>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <a href=\"#\">\n");
      out.write("              <span class=\"fa fa-twitter\"></span>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <a href=\"#\">\n");
      out.write("              <span class=\"fa fa-rss\"></span>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <a href=\"#\">\n");
      out.write("              <span class=\"fa fa-envelope\"></span>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <a href=\"#\">\n");
      out.write("              <span class=\"fa fa-instagram\"></span>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("      <!-- move icon -->\n");
      out.write("      <div class=\"text-center mt-md-4 mt-3\">\n");
      out.write("        <a href=\"#home\" class=\"move-top text-center mt-3\">\n");
      out.write("          <span class=\"fa fa-arrow-up\" aria-hidden=\"true\"></span>\n");
      out.write("        </a>\n");
      out.write("      </div>\n");
      out.write("      <!--//move icon -->\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("<!--//footer -->\n");
      out.write("  <!-- copy right -->\n");
      out.write("  <footer>\n");
      out.write("    <div class=\"bottom-footer text-center py-md-4 py-3\">\n");
      out.write("      <p>\n");
      out.write("        © 2019 Hippe. All Rights Reserved | Design by\n");
      out.write("        <a href=\"https://github.com/Melissa526/Team5_Festival\" target=\"_blank\">Power Rangers</a>\n");
      out.write("      </p>\n");
      out.write("    </div>\n");
      out.write("  </footer>\n");
      out.write("  <!-- copy right -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
